baseURL = "https://yurachud.github.io/"
relativeURLs = true
uglyURLs = true
languageCode = " lv-lv"
paginate = 6
theme = "portio"
title = "Annas prakse"
  # Main Menu
  [[menu.main]]
    name = "Atpakaļ"
    url = "#home"
    weight = 1
  [[menu.main]]
    name = "Par praksi"
    url = "#about"
    weight = 2
  [[menu.main]]
    name = "Pakalpojumi"
    url = "#resume"
    weight = 3
  # [[menu.main]]
  #   name = "Work"
  #   url = "#portfolio"
  #   weight = 4
  # [[menu.main]]
  #   name = "Resume"
  #   url = "#resume"
  #   weight = 5
  # [[menu.main]]
  #   name = "Blog"
  #   url = "#blog"
  #   weight = 6
  [[menu.main]]
    name = "Kontakti"
    url = "#contact"
    weight = 4

  # Sitemap Menu
  [[menu.sitemap]]
    name = "Par praksi"
    url = "#about"
    weight = 1
  [[menu.sitemap]]
    name = "Pakalpojumi"
    url = "#service"
    weight = 2
  # [[menu.sitemap]]
  #   name = "Privacy & Policy"
  #   url = "#"
  #   weight = 3
  # [[menu.sitemap]]
  #   name = "Latest Article"
  #   url = "#"
  #   weight = 4

[params]
  blogPageURL = "blog"
  contactLink = "contact"
  copyright = "All right reserved copyright © Portio 2020"
  footerLogo = "images/site-navigation/logo.png"
  formspreeURL = "YOUR FORMSPREE URL"
  googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
  logo = "images/site-navigation/logo.png"

  [params.address]
    address = "Rīga, Vienības gatve 109, Biznesa centrs Unity, 3. stāvs, kabinets 3.8."
    email = "anna.cudnovska@gmail.com"
    openingHours = "Darba dienās no 9.00 līdz 17.00"
    phone = "+(371) 2 789 42 92"
  [params.map]
    APIkey = "YOUR GOOGLE MAP API"
    latitude = "23.7783741"
    longitude = "90.3746808"
    pinImage = "images/pin.png"
